# Demonstrate configuration for ssl termination, used by front end app
server {
    listen 443 ssl;
    server_name hex0x0.site;
    
    # SSL Certificate paths
    ssl_certificate /etc/nginx/ssl/cert.crt;
    ssl_certificate_key /etc/nginx/ssl/cert.key;
    
    location / {
        # Pass original host and protocol info to the backend
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        # Forward traffic to backend via plain HTTP
        #
        # Prerequisites:
        #   1. create docker network
        #   2. nxgix and backend are deployed in the same instance and use same docker network
        proxy_pass http://192.168.100.1:3000/;
    }

    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root /usr/share/nginx/html;
    }
}